# Generated by Django 4.0.5 on 2022-06-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0002_book_user_alter_publication_address_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
